2020-04-25 10:58:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-25 10:59:19 WARNING (MainThread) [homeassistant.setup] Setup of updater is taking over 10 seconds.
2020-04-25 10:59:20 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2020-04-25 10:59:23 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform wake_on_lan is taking over 10 seconds.
2020-04-25 10:59:25 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2020-04-25 10:59:25 WARNING (MainThread) [homeassistant.components.light] Platform hue not ready yet. Retrying in 30 seconds.
2020-04-25 10:59:27 WARNING (MainThread) [homeassistant.setup] Setup of webostv is taking over 10 seconds.
2020-04-25 10:59:37 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds.
2020-04-25 11:05:16 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching group data
2020-04-25 11:05:16 WARNING (MainThread) [homeassistant.core] Unable to remove unknown listener <function async_track_point_in_utc_time.<locals>.point_in_time_listener at 0x67490198>
2020-04-25 11:05:18 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 177, in _async_callback_delayed_write
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 189, in _async_handle_write_data
    if "data_func" in data:
TypeError: argument of type 'NoneType' is not iterable
